import { IClient } from './IClient';
import { IDeliveryCommune } from './IDeliveryCommune';
import { ILogisticCenter } from './ILogisticCenter';
import { IMercadoLibreStatus } from './IMercadoLibreStatus';
import { IPackageInternalStatus } from './IPackageInternalStatus';
import { IPackageStatus } from './IPackageStatus';
import { ITag } from './ITag';

export interface IPackage {
	/** */
	id: number;
	/** */
	internal_id: string;
	/** */
	order_id: any;
	/** */
	welivery_id: any;
	/** */
	client_id: number;
	/** */
	user_id: number;
	/** */
	create_method: string;
	/** */
	driver_withdrawal_id: number;
	/** */
	rutero_withdrawal_id: any;
	/** */
	driver_delivery_id: any;
	/** */
	driver_return_id: any;
	/** */
	ecommerce_id: number;
	/** */
	logistic_center_id: number;
	/** */
	withdrawal_commune_id: any;
	/** */
	withdrawal_address: any;
	/** */
	withdrawal_detail: any;
	/** */
	delivery_commune_id: number;
	/** */
	delivery_address: string;
	/** */
	second_delivery_address: any;
	/** */
	address_geocoded: any;
	/** */
	second_address_geocoded: any;
	/** */
	tags_id: any;
	/** */
	delivery_detail: any;
	/** */
	package_status_id: number;
	/** */
	mercadolibre_status_id: number;
	/** */
	contact_name: string;
	/** */
	contact_lastname: any;
	/** */
	contact_email: any;
	/** */
	contact_phone: any;
	/** */
	package_internal_status_id: number;
	/** */
	modified_ml: any;
	/** */
	estimated_delivery_date: any;
	/** */
	estimated_handling_limit: any;
	/** */
	return_date_warehouse: any;
	/** */
	date_not_delivered: any;
	/** */
	date_cancelled: any;
	/** */
	date_delivered: any;
	/** */
	return_date: any;
	/** */
	dispatch_date_warehouse: any;
	/** */
	return_logistic_center_id: any;
	/** */
	products: any;
	/** */
	is_xl: boolean;
	/** */
	driver_delivery_address: any;
	/** */
	driver_delivery_address_geocoded: any;
	/** */
	order_route: any;
	/** */
	high_value: number;
	/** */
	is_change_tags_massive: boolean;
	/** */
	sentmail: boolean;
	/** */
	is_change_status_massive: boolean;
	/** */
	connection_id: any;
	/** */
	bsale_id: any;
	/** */
	created_at: string;
	/** */
	updated_at: any;
	/** */
	client: IClient;
	/** */
	packageStatus: IPackageStatus;
	/** In the tracking page the packageStatus objects comes with different nomenclature */
	package_status?: IPackageStatus;
	/** */
	tags: ITag[];
	/** */
	logistic_center?: ILogisticCenter;
	/** */
	deliveryCommune?: IDeliveryCommune;
	/** @deprecated delivery_commune */
	delivery_commune: IDeliveryCommune;
	/** */
	driver_full_name?: string;
	/** */
	mercadolibreStatus?: IMercadoLibreStatus;
	/** @deprecated mercadolibre_status */
	mercadolibre_status: IMercadoLibreStatus;
	/** */
	icon_class_internal_status:
	| 'icon--color-proceso'
	| 'icon--color-alert'
	| 'icon--color-ok';
	/** */
	package_internal_status: IPackageInternalStatus;
	/** */
	logistic_center_address: string;
	/** */
	package_status_name: string;
	/** */
	mercadolibre_status_name: string;
	/** */
	package_internal_status_name: string;
	/** */
	delivery_commune_name: string;
}
