import { IActions } from '../interfaces/communication/IActions';
import PARSERS from './PARSERS';

const ACTIONS: IActions = {
	GET_NOTIFICATIONS: {
		ACTION: 'GET_NOTIFICATIONS',
		SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
		FAILURE: 'GET_NOTIFICATIONS_FAILURE',
		PATH: '/api/notification',
		METHOD: 'POST',
		AUTH: true,
		PARSER: PARSERS.GET_NOTIFICATIONS,
	},

	READ_NOTIFICATION: {
		ACTION: 'READ_NOTIFICATION',
		SUCCESS: 'READ_NOTIFICATION_SUCCESS',
		FAILURE: 'READ_NOTIFICATION_FAILURE',
		PATH: '/api/notification/read/:id',
		METHOD: 'GET',
		AUTH: true,
		// PARSER: PARSERS.GET_NOTIFICATIONS
	},
};

export default ACTIONS;
