export const SET_FORM_DATA = 'SET_FORM_DATA';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';

export const SET_RESOURCES = 'SET_RESOURCES';
export const APPEND_RESOURCES = 'APPEND_RESOURCES';
export const SET_HEADER_COMPONENTS = 'SET_HEADER_COMPONENTS';
export const SET_PANEL_SETTINGS = 'SET_PANEL_COMPONENTS';

export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const UPDATE_THEME_SETTINGS = 'UPDATE_THEME_SETTINGS';
export const CONTENT_WIDTH = 'CONTENT-WIDTH';
export const CONTENT_HEIGHT = 'CONTENT-HEIGHT';
export const WINDOW_HEIGHT = 'WINDOW-HEIGHT';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';
export const SWITCH_THEME_TYPE = 'SWITCH_THEME_TYPE';
export const UPDATE_PAGE = 'UPDATE_PAGE';

export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

export const LOADING = 'LOADING';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

export const TOGGLE_NAV_EXPANDED = 'TOGGLE_NAV_EXPANDED';
export const SET_NAV_EXPANDED = 'SET_NAV_EXPANDED';
export const SET_NAV_SIZE = 'SET_NAV_SIZE';
