class AppLayoutSettings {
	static TAB_SIZE = 992;
	static MOBILE_SIZE = 575;
	static THEME_TYPE = 'THEME_TYPE';
	static THEME_TYPE_LIGHT = 'light';
	static THEME_TYPE_DARK = 'dark';
	static THEME_TYPE_DASH_DEFAULT = 'light';
	static THEME_TYPE_SEMI_DARK = 'THEME_TYPE_SEMI_DARK';
	static THEME_COLOR = 'THEME_COLOR';
	static UPDATE_RTL_STATUS = 'UPDATE_RTL_STATUS';
	static LAYOUT_TYPE = 'LAYOUT_TYPE';
	static LAYOUT_TYPE_FRAMED = 'framed-layout';
	static LAYOUT_TYPE_BOXED = 'boxed-layout';
	static LAYOUT_TYPE_FULL = 'full-layout';
	static NAV_STYLE = 'NAV_STYLE';
	static NAV_STYLE_FIXED = 'NAV_STYLE_FIXED';
	static NAV_STYLE_MINI_SIDEBAR = 'NAV_STYLE_MINI_SIDEBAR';
	static NAV_STYLE_DRAWER = 'NAV_STYLE_DRAWER';
	static NAV_STYLE_NO_HEADER_MINI_SIDEBAR = 'NAV_STYLE_NO_HEADER_MINI_SIDEBAR';
	static NAV_STYLE_NO_HEADER_EXPANDED_SIDEBAR =
		'NAV_STYLE_NO_HEADER_EXPANDED_SIDEBAR';
	static NAV_STYLE_DEFAULT_HORIZONTAL = 'NAV_STYLE_DEFAULT_HORIZONTAL';
	static NAV_STYLE_DARK_HORIZONTAL = 'NAV_STYLE_DARK_HORIZONTAL';
	static NAV_STYLE_INSIDE_HEADER_HORIZONTAL =
		'NAV_STYLE_INSIDE_HEADER_HORIZONTAL';
	static NAV_STYLE_BELOW_HEADER = 'NAV_STYLE_BELOW_HEADER';
	static NAV_STYLE_ABOVE_HEADER = 'NAV_STYLE_ABOVE_HEADER';
	static NAV_STYLE_COLLAPSABLE = 'NAV_STYLE_COLLAPSABLE';

	
}

export default AppLayoutSettings;
